name: integration
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: install dependency
        run: npm install  
      - name: run tsc
        run: npm run lint:tsc
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: install dependency
        run: npm install
      - name: run unit test
        run: npm run test
